server:
  servlet:
    context-path: /api
  port: 8090

spring:
  profiles:
    active: local
  application:
    name: demo
  redis:
    database: 8
    host: 172.16.7.200
    password: 123456
    port: 6379
  rabbitmq:
    host: 172.16.6.55
    port: 5672
    username: admin
    password: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
          jwk-set-uri: http://localhost:8080/oauth2/jwks
logging:
  level:
    root: error
