<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.etd.framework</groupId>
        <artifactId>etd-framework-starter</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>org.etd.framework</groupId>
    <artifactId>etd-framework-starter-event-bus</artifactId>
    <packaging>pom</packaging>
    <name>etd-framework-starter-event-bus</name>

    <modules>
        <module>etd-framework-event-core</module>
        <module>etd-framework-starter-event-client</module>
        <module>etd-framework-starter-event-server</module>
    </modules>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.etd.framework</groupId>
                <artifactId>etd-framework-dependencies</artifactId>
                <version>0.0.1-SNAPSHOT</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
