server:
  servlet:
    context-path: /
  port: 8100

logging:
  level:
    root: DEBUG
spring:
  profiles:
    active: local
  application:
    name: UPMS
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    connect-timeout: 3s
    database: 4
    lettuce:
      pool:
        enabled: true
        min-idle: 10
        max-idle: 20
        max-active: 20
        max-wait: 5s



system:
  oauth:
    access-token:
      expired: 30
      timeUnit: minutes

    refresh-token:
      expired: 60
      timeUnit: minutes
