server:
  servlet:
    context-path: /upms/apis
  port: 8100

logging:
  level:
    root: DEBUG
spring:
  profiles:
    active: dev




system:
  oauth:
    access-token:
      expired: 30
      timeUnit: minutes

    refresh-token:
      expired: 60
      timeUnit: minutes
