apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
spec:
  type: NodePort
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30090
