<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>etd-framework-parent</artifactId>
        <groupId>org.etd.framework</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>


    <modelVersion>4.0.0</modelVersion>
    <groupId>org.etd.framework</groupId>
    <artifactId>etd-framework-dependencies</artifactId>
    <packaging>pom</packaging>


    <properties>
        <!--   SpringCloud相关依赖     -->
        <spring.boot.version>3.5.16</spring.boot.version>
        <spring.cloud.version>2025.0.3</spring.cloud.version>

        <java.version>21</java.version>

        <!--第三方工具类-->
        <hutool.version>5.8.38</hutool.version>
        <jakarta.validation.version>3.1.1</jakarta.validation.version>
        <commons.lang3.version>3.18.0</commons.lang3.version>

        <!--Mybatis-->
        <mybatis.version>3.5.14</mybatis.version>
        <!--德鲁伊-->
        <druid.version>1.2.27</druid.version>
        <!--缓存框架-->
        <fasterxml.version>2.19.2</fasterxml.version>
        <fastjson.version>2.0.58</fastjson.version>
        <caffeine.version>3.2.2</caffeine.version>
        <commons.pool2.version>2.12.1</commons.pool2.version>
        <alibaba.transmittable.version>2.14.5</alibaba.transmittable.version>


        <!--第三方开源SDK https://github.com/Wechat-Group/WxJava-->
        <weixin.java.version>4.0.0</weixin.java.version>

        <oauth2.authorization.version>1.5.2</oauth2.authorization.version>

        <guava.version>33.4.8-jre</guava.version>
        <gson.version>2.13.1</gson.version>

        <minio.version>8.5.17</minio.version>
        <alibaba.oss.version>3.18.3</alibaba.oss.version>

        <drools.verson>7.73.0.Final</drools.verson>

        <org.mapstruct.version>1.6.3</org.mapstruct.version>
        <lombok.version>1.18.38</lombok.version>
        <mysql.version>9.4.0</mysql.version>
    </properties>


    <dependencyManagement>

        <dependencies>

            <!--    Spring jar包管理        -->
            <dependency>
                <!-- Import dependency management from Spring Boot -->
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring.cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.security</groupId>
                <artifactId>spring-security-oauth2-authorization-server</artifactId>
                <version>${oauth2.authorization.version}</version>
            </dependency>


            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-3-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>


            <!--   本地工程jar包管理     -->
            <dependency>
                <groupId>org.etd.framework</groupId>
                <artifactId>etd-framework-starter-web</artifactId>
                <version>${etd.framework.version}</version>
            </dependency>

            <dependency>
                <groupId>org.etd.framework</groupId>
                <artifactId>etd-framework-common-core</artifactId>
                <version>${etd.framework.version}</version>
            </dependency>

            <dependency>
                <groupId>org.etd.framework</groupId>
                <artifactId>etd-framework-common-utils</artifactId>
                <version>${etd.framework.version}</version>
            </dependency>

            <dependency>
                <groupId>org.etd.framework</groupId>
                <artifactId>etd-framework-starter-cache</artifactId>
                <version>${etd.framework.version}</version>
            </dependency>

            <dependency>
                <groupId>org.etd.framework</groupId>
                <artifactId>etd-framework-starter-message</artifactId>
                <version>${etd.framework.version}</version>
            </dependency>


            <dependency>
                <groupId>org.etd.framework</groupId>
                <artifactId>etd-framework-starter-logs</artifactId>
                <version>${etd.framework.version}</version>
            </dependency>

            <dependency>
                <groupId>org.etd.framework</groupId>
                <artifactId>etd-framework-starter-security-oauth</artifactId>
                <version>${etd.framework.version}</version>
            </dependency>

            <!--     其他第三方jar包管理       -->
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-core</artifactId>
                <version>${hutool.version}</version>
            </dependency>

            <dependency>
                <groupId>jakarta.validation</groupId>
                <artifactId>jakarta.validation-api</artifactId>
                <version>${jakarta.validation.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons.lang3.version}</version>
            </dependency>


            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-jsqlparser</artifactId>
                <version>${mybatis.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid</artifactId>
                <version>${druid.version}</version>
            </dependency>


            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>${fasterxml.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-yaml</artifactId>
                <version>${fasterxml.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>${fasterxml.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>${fasterxml.version}</version>
            </dependency>


            <dependency>
                <groupId>com.github.ben-manes.caffeine</groupId>
                <artifactId>caffeine</artifactId>
                <version>${caffeine.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-pool2</artifactId>
                <version>${commons.pool2.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson.version}</version>
            </dependency>




            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>transmittable-thread-local</artifactId>
                <version>${alibaba.transmittable.version}</version>
            </dependency>


            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>



            <!--第三方开源微信支付 SDK https://github.com/Wechat-Group/WxJava-->
            <dependency>
                <groupId>com.github.binarywang</groupId>
                <artifactId>weixin-java-pay</artifactId>
                <version>${weixin.java.version}</version>
            </dependency>


            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>${gson.version}</version>
            </dependency>


            <dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>${minio.version}</version>
            </dependency>

            <dependency>
                <groupId>com.aliyun.oss</groupId>
                <artifactId>aliyun-sdk-oss</artifactId>
                <version>${alibaba.oss.version}</version>
            </dependency>

            <dependency>
                <groupId>org.drools</groupId>
                <artifactId>drools-bom</artifactId>
                <type>pom</type>
                <version>${drools.verson}</version>
                <scope>import</scope>
            </dependency>

            <!--mysql驱动-->
            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>${mysql.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${org.mapstruct.version}</version>
            </dependency>


            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>


        </dependencies>

    </dependencyManagement>


</project>
