server:
  port: 8080
  error:
    include-message: always
logging:
  level:
    root: TRACE
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security.oauth2: DEBUG

oauth2:
  authorization:
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmL2dIkc3OpZfHOF/7TD8+FWYGlG+CSzhPfNmm6tIDqoVBYKYSIIAMHRAtGjf8M1i5h1rQeEyd8lEJ8YyA25WFNpeTHdZP3YsDM6HVhclWLJZs6KJ55DU4ySGvDDP/i2WplOQ5HV8I/sm2IvFFZ8bxxYvLIqz5U07/e1W+qKtyscRjTRgiK3zhomQ/71BDFtitQns8crrfLTkJkDpNG8qRm1pQE1dl8CXjapVy0fyKb+zzDthdQnpVzI77WerRktTA2iU/WK2yM0cxJ02/lPTAJZ1pKzlWA+cBECjkH8jTLPuk1nWo6ejOoHSz10KRoJEDrJzdDV0T5TY2yqB3DYB/wIDAQAB
    privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCYvZ0iRzc6ll8c4X/tMPz4VZgaUb4JLOE982abq0gOqhUFgphIggAwdEC0aN/wzWLmHWtB4TJ3yUQnxjIDblYU2l5Md1k/diwMzodWFyVYslmzoonnkNTjJIa8MM/+LZamU5DkdXwj+ybYi8UVnxvHFi8sirPlTTv97Vb6oq3KxxGNNGCIrfOGiZD/vUEMW2K1Cezxyut8tOQmQOk0bypGbWlATV2XwJeNqlXLR/Ipv7PMO2F1CelXMjvtZ6tGS1MDaJT9YrbIzRzEnTb+U9MAlnWkrOVYD5wEQKOQfyNMs+6TWdajp6M6gdLPXQpGgkQOsnN0NXRPlNjbKoHcNgH/AgMBAAECggEASbNcyfiBHsUGOgJZXxM/TXjHvxNoVjcQrHrxLPY1+9V39UOxxXLtMnQ18JeWTzRbn1vcsFpApuo399U7tsobwU4pKE6Cgwu7b6aMSS879xOAExy/3DvXbY7ncJFBG43V3oX+KS7Dav06Hk07GRbAKY17z8tRyLg+1WUbji7HG0u6Q6E6oszk7VM74L7pchV2t05pwCu+DNcTQN36SLY0WiIA1gB9Ecv/adpov2jTWL8EFCCyFFodMHoBbSfu09oise6F5Dq+N6+yL1DrZ5lOlvebnuAjR24Me9CkTP7PqQ9eWS1Acb3FNQ8eyVxNZsl2FAodBES7WLyRPYnhdhmXuQKBgQDIitIbDO61bybgMxN+y5TvRSfQTQTtyoZRbRzcvk5vBObvTGGKUFZ5EN8m/9A34wwPw/8cWADm/Mu0I8ARqsRXNfwUR0nneywfhLeHUzxoNX7DDcXa8iMI0yhMp65xTmPP0IH/s7xAs0+Ia6b0QeUxdTd14R5gdzcqW055Xwk3pQKBgQDC+rrRA9eYe4YjfJ4mAyl7tl5eCIlrbJGcdmBbpRGoSSgHJOlpjRMdzPKJomtka4yGe57gx2q9gVqXLPtlN0x7ZKChXKmE4QWj3EItmIPSHtZtjmmTx7atOkQgXaFrzKnvXcq0MSA/gken0Ha7yUifcFSBMbRwQhebt6K529eB0wKBgQCR1foi982kHZfM1Pfpbkz5j3X7kfbyoiP5lPq3QKGzNIJoJUiNmAy6b92H8+JMsg00bdjYmNrXH6FXd+QWNPQhY73UVV9WOgmFRjNc8tfsBHMRj7OBnDKEGWKmFA7UkSgemUfgVqmg94Tv9TFtUXpF9DMHw1Ue27M/VzUDKGyAjQKBgFyLKRR/4FqtdnNteJrOMWhYnN3A64ijVVGQFhgpdwILBwatDGRe403nss6E2rglG+PQ1Q4XWKBtvxO18/SMlK6UinFMS+GX9Fdb+cUueJLItDn3uEC+MAR0fVVnW3CRCa9lMwrnrki2i1Apb9GdreyPImzXrK8Dj7UHKiNRJy6lAoGAKCWf7IhiBlMPn1lfbI8QZ4Dgl61iUy6GTzHl1rLuKt0cE9njlPGMOVxNlA7zwJfPCn0TfiKYQO5NAiOw4L+5I+DTuVHcK7n6XoZmudPrERhuavzeCfWdICFu9Of2VHEpBo9SICB/FBmbiSTiGxiOot7Zcf9D8GyYKUHx+o95xjo=


spring:
  profiles:
    active: dev