apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          command:
            - "redis-server"
            - "--appendonly"
            - "yes"
            - "--requirepass"
            - "123456"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data-volume
              mountPath: /data
              subPath: redis
      volumes:
        - name: redis-data-volume
          hostPath:
            path: /Users/a123/k8s-configs/redis/redis-data
            type: DirectoryOrCreate
